name: text_helpers
description: Solve text overflow problems.
version: 1.0.1
homepage: https://github.com/davidsdearaujo/text_helpers
git: https://github.com/davidsdearaujo/text_helpers

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: